### ISSUE TITLE
Values calculate

### ISSUE THREAD

**Issue by xpix** [andremiller/pimatic-mqtt-simple#1]
Hi,

wonderful plugin. Can we calculate the result. I get my values so: Battery: 2990 mV and percent: 299. I have to calculate Battery in Volt = value /1000 and Perent / 10. How can i add this to the config?

**Comment by andremiller** [comment]
Hi @xpix, is this still an issue, or did #3 resolve it?

**Comment by xpix** [comment]
Yes, are resolbved with my Pullrequest :)
