### ISSUE TITLE
How about string instead of numbers?

### ISSUE THREAD

**Issue by sebastienvg** [andremiller/pimatic-mqtt-simple#4]
First, thank you for the plugin works great. I would like to use it to display say GPS coordinate published from another mqtt client set up in my car on the topic location/dodge_charger

What should be the device in the config.json?

**Comment by andremiller** [comment]
Is it returning the GPS coordinate as a string, that you just wish to display as is?

I think there's currently a bug with displaying strings, which I'm busy l looking at for issue #5

**Comment by sebastienvg** [comment]
Yup, that's exactly what I meant! Thanks for looking into this.

**Comment by andremiller** [comment]
This should now be resolved with commit 47fe0b4 and available as v0.1.1 on NPM : https://www.npmjs.com/package/pimatic-mqtt-simple

You can install it or update it by going to your pimatic-app directory (the one with config.json and node_modules) and running
npm install pimatic-mqtt-simple

**Comment by sebastienvg** [comment]
Yup it's working fine, thank you for your work.
