### ISSUE TITLE
error [pimatic]: [Error: Couldn't find plugin info for pimatic-mqtt-simple]

### ISSUE THREAD

**Issue by xpix** [andremiller/pimatic-mqtt-simple#6]
Hello, some info fails in pimatic :)

**Comment by andremiller** [comment]
Thanks @xpix

When do you get this error message? Is this using the version from npm?

**Comment by xpix** [comment]
Hmm, no i'll try your version at this weekend.

**Comment by andremiller** [comment]
Hi @xpix. I can't replicate this issue. I installed a new version of pimatic and used the plugin from npm (by running npm install pimatic-mqtt-simple) and it worked.

Could you give that a go and see what you get?

**Comment by xpix** [comment]
I dont find this issue after an update. Good work!
